// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vatsal278/TransactionManagementService/internal/logic (interfaces: TransactionManagementServiceLogicIer)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	model "github.com/PereRohit/util/model"
	gomock "github.com/golang/mock/gomock"
	model0 "github.com/vatsal278/TransactionManagementService/internal/model"
)

// MockTransactionManagementServiceLogicIer is a mock of TransactionManagementServiceLogicIer interface.
type MockTransactionManagementServiceLogicIer struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionManagementServiceLogicIerMockRecorder
}

// MockTransactionManagementServiceLogicIerMockRecorder is the mock recorder for MockTransactionManagementServiceLogicIer.
type MockTransactionManagementServiceLogicIerMockRecorder struct {
	mock *MockTransactionManagementServiceLogicIer
}

// NewMockTransactionManagementServiceLogicIer creates a new mock instance.
func NewMockTransactionManagementServiceLogicIer(ctrl *gomock.Controller) *MockTransactionManagementServiceLogicIer {
	mock := &MockTransactionManagementServiceLogicIer{ctrl: ctrl}
	mock.recorder = &MockTransactionManagementServiceLogicIerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionManagementServiceLogicIer) EXPECT() *MockTransactionManagementServiceLogicIerMockRecorder {
	return m.recorder
}

// HealthCheck mocks base method.
func (m *MockTransactionManagementServiceLogicIer) HealthCheck() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockTransactionManagementServiceLogicIerMockRecorder) HealthCheck() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockTransactionManagementServiceLogicIer)(nil).HealthCheck))
}

// Ping mocks base method.
func (m *MockTransactionManagementServiceLogicIer) Ping(arg0 *model0.PingRequest) *model.Response {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", arg0)
	ret0, _ := ret[0].(*model.Response)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockTransactionManagementServiceLogicIerMockRecorder) Ping(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockTransactionManagementServiceLogicIer)(nil).Ping), arg0)
}
